### ISSUE TITLE
confusing example

### ISSUE THREAD

**Issue by Chunpai** [CAHLR/pyBKT#14]
Thanks for releasing this wonderful package. One thing I get confused from the Internal Data example in README file is:
the resource for the example matrix is shown as below
| 1  2  1  1  3 |
however, if 1 represents the learning resource such as watching video, then the first, third, fourth columns should not have student responses. But how come does it have correct response at column 3 in the data matrix?

I am looking forward to your illustration. Thanks.

Best,
Chunpai

**Comment by fredwang25** [comment]
Hi! The all-zero columns correspond with videos that do not ask a question at the end, while the third column is a video that does have a question asked at the end. However, this internal data format is mostly deprecated now, since we have abstracted it away with our new Model class. Hope this helps!
