### ISSUE TITLE
Difference between correct and state prediction

### ISSUE THREAD

**Issue by NihadR** [CAHLR/pyBKT#15]
Hello I am using this model in a project I am doing and am confused between the meaning of correct and state prediction when using the predict function. Could this be clarified please?

Many thanks, 

Nihad

**Comment by zpardos** [comment]
Hi Nihad,

State predictions are those made about the hidden state of the model. The interpretation of the hidden state is meant to be the cognitive mastery state. If the hidden state is above a threshold (e.g., 0.95 or 0.98), then the student is assumed to have mastered the skill. Since we never observe the true state, these would be better referred to as hidden state estimates. 

The correct predictions are the model's prediction that the student will answer a question correct at that time slice. These are directly compared to actual responses to calculate the error metric when using crossval.

**Comment by mdgbayly** [comment]
I had a similar question. Sorry if this is dumb question as still very new to BKT. So just to clarify, is state_prediction equivalent to P(Lt+1) as shown in this equation for classical BKT?

![image](https://user-images.githubusercontent.com/493938/113440523-719c0480-93a1-11eb-99a3-cd846e714a99.png)

**Comment by zpardos** [comment]
Yes, p(Lo) is the hidden state prior and p(Lt|obs) is the posterior, or hidden state estimate after observation(s). This is what is being generated by state_prediction.
