### ISSUE TITLE
Question: Could you clarify the meaning of the multi-prior model?

### ISSUE THREAD

**Issue by mdgbayly** [CAHLR/pyBKT#18]
Thanks for this great library.

I was trying to understand the implications of choosing the different models in particular `multiprior`.

The comment in the colab tutorial states
```
# The multiprior model generates different priors based on the first 
# response of each student.
```

However, when I run this on the assistments and cognitive tutor datasets and then output the params it shows output like the following which implies that multiprior is being used to set different `learns` rates rather than different `prior`s. 
I also wasnt clear on what the class values of  `1` and `2` represented given the unique values for the `correct` column are `0` and `1`.

			
skill | param | class | value
-----|------|-------|------	
Calculations with Similar Figures | prior | default | 0.29272
&nbsp; | learns | 2 | 0.48593
&nbsp; |&nbsp;  | 1 |  0.08164
&nbsp; |&nbsp;  | N/A | 0.10794

**Comment by fredwang25** [comment]
Hi! Thanks for letting us know, this is a small issue on our end. Internally we represent incorrect and correct as 1 and 2, respectively, instead of 0 and 1. We'll fix the issue soon, but for now just know that class 2 is correct first response and class 1 is incorrect first response.

**Comment by zpardos** [comment]
Hi Martin, let me add to that answer and address other questions you had.

Q: If this is multi "prior" then why are there multiple learns instead of multiple priors?
A: The inference engine currently only supports multiple learn rates and not multiple priors. Nevertheless, you can effectively get multiple priors by creating a dummy time slice before the actual first observed time slice, setting an actual prior of 0, and then specifying learn rates for every prior class you want that will only be applied once, after the dummy time slice. Therefore, learns 1 in the table is the prior of students who answer wrong on the very first question and learns 2 is the prior of students who answer correctly. The "N/A," which is poorly named here, is the standard learn rate, p(T), that will be applied after all subsequent time slices.
