### ISSUE TITLE
Issues with a degenerate model

### ISSUE THREAD

**Issue by chssaine16** [CAHLR/pyBKT#21]
Hi there!

I'm currently fitting a BKT model to a dataset (that's modeled similarly to the assisstments dataset you use) using pyBKT. 

This issue I'm seeing is that all my state predictions actually decrease when they should be increasing (increasednexposure to the knowledge content, and simultaneously are answering each of the assessments for that one knowledge content correctly).

I've read a few papers on how to identify degenerate models and one of them would be that your guess and slip parameters are very high (which are not the case here). I've retrained the model on a number of different skills and users and still getting decreasing state predictions.

Lastly, when I try to compute the probabilities by hand (using the trained parameters) I'm also seeing that the P(Ln-1|Correctn) is different from what's provided.

Are these issues that you've encountered before? If you have any additional ways to debug this, I'd be very thankful!

**Comment by abadrinath947** [comment]
This was a bug that was identified recently, sorry about that. Instead of the mastery predictions, I had instead set the column to 1 - mastery predictions (the internal prediction helper returns both the probability and its complement, and I chose the wrong one). This has since been fixed on the Git repository (but a new pip version has not been created yet). To install the current version, try `git clone https://github.com/CAHLR/pyBKT && cd pyBKT` and then `pip uninstall -y pyBKT && pip install .`.

Hope that helps.

**Comment by chssaine16** [comment]
Wow thank you so much! I was spinning my wheels on this one for some time. I'll download the version and let you know :)

**Comment by themrzmaster** [comment]
Hi @abadrinath947 !

I am still having the same problem:



<img width="986" alt="Screen Shot 2023-02-16 at 10 11 04" src="https://user-images.githubusercontent.com/852747/219373996-77ec03ce-f45d-414e-bbb7-f32072532d51.png">
<img width="901" alt="Screen Shot 2023-02-16 at 10 11 47" src="https://user-images.githubusercontent.com/852747/219374107-93d2953b-c171-4a4d-944a-7b783e2878d6.png">

When a student gets all right the state prediction is low.
Also, when he do something wrong, the state prediction increases. 
I am using the lastest git version
