### ISSUE TITLE
Fair evaluation of 'Multi-prior' model 

### ISSUE THREAD

**Issue by WoodyAhn** [CAHLR/pyBKT#23]
Firstly, thanks for providing a great library.

I read that 'multi-prior' model estimates different initial parameters for each student depending on their first response (whether correct/incorrect).

And I think the cross-validation procedure in pyBKT is as follows:
1. Splits the data based on the users (so, in the case of 5-folds CV, split the data into 5 with disjoint user_id) 
2. Estimate the model parameters using only the train-set
3. Predict the test-set by using the trained model
4. Evaluate the prediction results based on the specific measure (e.g., auc, rmse, ...)

In this case, 
- How to estimate the initial parameter for students in the test-set (since they were not in the train-set)?
- If the initial parameters are set based on the first response of the student in the test-set, It would not be a fair evaluation cause it uses the information of the test-set before the prediction
- To be a fair evaluation, I think the first response for each student in the test-set should not be incorporated in the evaluation.

I ask these questions cause I got the suspicious results after fitting cross-validation.
The CV results (AUC) are as follows:
Baseline: 0.6093
Forgets: 0.6144
Multilearn+Forgets: 0.6158
Multiprior+Forgets: 0.7919

Multi-prior model  works dramatically better than others.
However, I thought that it could be because of the reasons I wrote above (every first response is predicted correctly since the model sets the initial parameter values based on the first response of the student)

Please correct my assumptions if I were wrong
- In CV, split the data into k with "disjoint user_id"
- Set initial parameter of the students in the test-set based on their first response

And if the assumptions are not wrong, could you give me a solution to tackle this problem?

Again, thanks for providing and maintaining this wonderful library.

**Comment by zpardos** [comment]
Hi Jay Ahn,

You are correct that a standard CV evaluation of this prior setting heuristic would be unfair since it is essentially peeking at the first response while also predicting the first response. The solution in our paper, and the original paper the technique was proposed in (Pardos & Heffernan, 2010), was to only evaluate the multi-prior model and baselines on the last response of the test set response sequences. It would also suffice to just not include prediction of the first response as part of the error metric calculation. To do either of these custom evaluations, you'll need to use the predict function and manually manage the CV fold assignments.

**Comment by WoodyAhn** [comment]
Thank you for your detailed reply!
I will consider to manage the CV function
