### ISSUE TITLE
Issue with Roster init from a multigs model

### ISSUE THREAD

**Issue by DnzzL** [CAHLR/pyBKT#29]
Hello everyone,
and thanks a lot for this wonderful package ! 👍 

I've gotten used to Roster with a pretty simple Model, but I've seen huge improvements in accuracy with multigs.

The thing is, when I create a new Roster object from the trained model with multigs, I've got the error `KeyError: True`
from https://github.com/CAHLR/pyBKT/blob/9698ac04d59cce51ca3a89ee67f633b7446c200b/source-py/pyBKT/models/Roster.py#L561 .

Am I doing something wrong or is there an issue with the initialization ?
Thanks

**Comment by abadrinath947** [comment]
Hi,

Apologies for the slow response. There was a small bug where the roster was being improperly initialized, but this code to handle multigs should be fine. I've added better error messages to the github repo. Please pull and reinstall using `pip`.

Please keep in mind that Roster multigs/learn are not very heavily tested since it was not part of our paper. As such, it would be good to verify that based on the parameter values, the appropriate values are being outputted. Please let me know if there are any incorrect updates in Roster using multigs/learn, and I can take a look.

Here is an example of how you would use multigs in Roster:
```
from pyBKT.models import *
model = Model()
model.fit(data_path = 'ct.csv', multigs = True)
roster = Roster(students = ['Jeff', 'Bob'], skills = 'Calculate unit rate', model = model)
roster.update_state('Calculate unit rate', 'Jeff', correct = 1, multigs = 'RATIO2-001')
```
