### ISSUE TITLE
Unable to install Python/C++ version on Windows

### ISSUE THREAD

**Issue by zhermin** [CAHLR/pyBKT#32]
Hi, thanks for the amazing library, especially the demo on Google Colab. I have been trying to install the C++ version on my Windows machine to no avail (verified using `pyBKT.version`), despite installing the gcc and g++ compilers for Windows (able to run both of them on CMD). I was able to install the C++ version on my Mac as there are installation instructions for Linux and Mac but none explicitly for Windows (discounting WSL) on the README and have also tried to find solutions on closed GitHub issues. 

Here are some of the things I have tried to install the C++ version on Windows: 
- Installed gcc and g++ for Windows using MinGW C Compiler and added both of them to my env variables
- Tried installing using `pip install pyBKT`, `git clone` then `pip install .` and also `python setup.py install`
- Tried using other versions of `Python=3.7, 3.8, 3.9` in Conda environments
- Couldn't find a `setup_conda.sh` file either for Conda installation mentioned in the README

**Comment by abadrinath947** [comment]
Hi @zhermin ,

Thank you for your great question. I have tried at length to try and get this work as well, using the methods you've mentioned. I've also tried with Microsoft Visual C++ and whatnot, but to no avail. As of now, I don't believe there is a clean enough way to make the C++ version work on Windows. Hence, we do not officially support or give any instructions for installing this version on Windows.

As for `conda`, that installation method was deprecated as it was not necessary anymore. In any case, this would not have solved your issue of not having `gcc` since it would not be available for Windows systems.

In any case, here was the old Conda setup file (which assumed prior installation of `gcc`):

```
name: pyBKT
channels:
  - defaults
dependencies:
  - python=3.6.10
  - boost=1.73.0
  - pip=21.0.1
  - pip:
    - sklearn==0.0
    - requests==2.25.1
```
Please let me know if you have any other questions, and apologies for the late response.

Sincerely,
Anirudhan

**Comment by zhermin** [comment]
Hey @abadrinath947, thanks a lot for the detailed response from your side as well! I think it would be great to include in the README perhaps that as of now the only solutions to running the C++ version on "Windows" would be either WSL or online through Google Colab. However, no worries from my side because my team and I will be deploying this pyBKT model to the cloud and those systems would definitely be UNIX-based and likely be able to install the C++ version. Thanks a lot again for the great library, I will open a new issue if I have any further questions.
